### PR TITLE
Update Dojo stage values

### PR DESCRIPTION
**Pull request by kennanseno**
https://github.com/CoderDojo/community-platform/issues/636

### CODE REVIEW

**Comment by daveymoran-nearform** [comment]
also needs localisation :)

**Comment by daveymoran-nearform** [comment]
lgtm

**Comment by kennanseno** [comment]
updated it in this pr https://github.com/CoderDojo/cp-zen-platform/pull/648

**Comment by daveymoran-nearform** [comment]
@kennanseno its best to update the original PR with any updates from comments.
in this case you have commits relating to issue#636 in a PR associated with issue#573

**Comment by kennanseno** [comment]
@daveymoran-nearform should I have made a separate pr for the changes I made in messages.po for issue#636? I only did that cause this pr is in dojo-service repo and the message.po is in zen-platform repo.

**Comment by kennanseno** [comment]
@daveymoran-nearform asked @dberesford on how I should have done it. fixing it up now. :)

**Comment by kennanseno** [comment]
just made a pr there for it @daveymoran-nearform . thanks btw :)

**Comment by daveymoran-nearform** [comment]
no bothers @kennanseno, fair play to ya :)

**Pull request merged**
